# https://docs.github.com/en/actions/creating-actions/creating-a-composite-action
name: Deploy preview
description: Deploy preview to GitHub Pages

inputs:
  json:
    description: "JSON stringified object containing all the inputs from the calling workflow"
    required: true
  secrets:
    description: "JSON stringified object containing all the secrets from the calling workflow"
    required: true

runs:
  using: "composite"
  steps:
    - name: Setup Node.js 18.x
      uses: actions/setup-node@v3
      with:
        node-version: 18
        cache: npm

    - name: Copy CHANGELOG.md
      shell: bash
      run: cp -v ./CHANGELOG.md ./src/pages/CHANGELOG.md

    - name: Install dependencies
      shell: bash
      run: npm ci

    - name: Build website
      shell: bash
      run: npm run build

    # https://github.com/crazy-max/ghaction-import-gpg
    # import gpg key for verified commits
    - name: Import GPG key
      id: gpg
      uses: crazy-max/ghaction-import-gpg@v4
      with:
        gpg_private_key: ${{ fromJSON(inputs.secrets).GPG_PRIVATE_KEY }}
        passphrase: ${{ fromJSON(inputs.secrets).GPG_PASSPHRASE }}
        git_config_global: true
        git_user_signingkey: true
        git_commit_gpgsign: true

    - name: Export env vars
      shell: bash
      env:
        source_folder: ./build
        target_branch: gh-pages
        # deploy to a folder called gh-preview/pr-#
        target_folder: gh-preview/pr-${{ github.event.number }}
        published_url: https://handbook.balena.io/gh-preview/pr-${{ github.event.number }}/
      run: |
        echo "source_folder=${source_folder}" >> $GITHUB_ENV
        echo "target_branch=${target_branch}" >> $GITHUB_ENV
        echo "target_folder=${target_folder}" >> $GITHUB_ENV
        echo "published_url=${published_url}" >> $GITHUB_ENV

    # https://github.com/JamesIves/github-pages-deploy-action
    - name: Deploy preview to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@v4

      with:
        folder: ${{ env.source_folder }}
        branch: ${{ env.target_branch }}
        target-folder: ${{ env.target_folder }}
        token: ${{ fromJSON(inputs.secrets).FLOWZONE_TOKEN }}
        # use embedded name and email from gpg key for commit
        git-config-name: ${{ steps.gpg.outputs.name }}
        git-config-email: ${{ steps.gpg.outputs.email }}
        force: false
        commit-message: |
          Deploying preview of ${{ github.repository }}@${{ github.event.pull_request.head.sha }} to ${{ env.target_branch }} 🚀

          View at ${{ env.published_url }}

    - name: Create pull request comment
      uses: marocchino/sticky-pull-request-comment@v2
      with:
        header: gh-preview
        GITHUB_TOKEN: ${{ fromJSON(inputs.secrets).FLOWZONE_TOKEN }}
        message: |
          :rocket: Deployed ${{ github.repository }}@${{ github.event.pull_request.head.sha }} to ${{ env.published_url }}
