# https://docs.github.com/en/actions/creating-actions/creating-a-composite-action
name: Deploy to GitHub Pages
description: Deploy to GitHub Pages

inputs:
  flowzone_token:
    description: "Flowzone token"
    required: true
  shell:
    description: "Shell"
    required: false
    default: bash

runs:
  using: "composite"
  steps:
    - name: Setup Node.js 18.x
      uses: actions/setup-node@v3
      with:
        node-version: 18
        cache: npm

    - name: Install dependencies
      shell: bash
      run: npm ci

    - name: Build website
      shell: bash
      run: npm run build

    # Popular action to deploy to GitHub Pages:
    # Docs: https://github.com/peaceiris/actions-gh-pages#%EF%B8%8F-docusaurus
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ inputs.flowzone_token }}
        # Build output to publish to the `gh-pages` branch:
        publish_dir: ./build
        # The following lines assign commit authorship to the official
        # GH-Actions bot for deploys to `gh-pages` branch:
        # https://github.com/actions/checkout/issues/13#issuecomment-724415212
        # The GH actions bot is used by default if you didn't specify the two fields.
        # You can swap them out with your own user credentials.
        user_name: github-actions[bot]
        user_email: 41898282+github-actions[bot]@users.noreply.github.com
